"""create_initial_tables

Revision ID: 196f3771af66
Revises: 
Create Date: 2026-01-21 19:27:33.570720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '196f3771af66'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('enunciado', sa.Text(), nullable=False),
    sa.Column('alternativas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gabarito', sa.String(length=1), nullable=False),
    sa.Column('explicacao', sa.Text(), nullable=True),
    sa.Column('imagem_url', sa.String(length=255), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('materia', sa.Enum('LINGUAGENS', 'HUMANAS', 'NATUREZA', 'MATEMATICA', name='materia'), nullable=False),
    sa.Column('topico', sa.String(length=100), nullable=True),
    sa.Column('subtopico', sa.String(length=100), nullable=True),
    sa.Column('dificuldade', sa.Enum('FACIL', 'MEDIA', 'DIFICIL', name='dificuldade'), nullable=True),
    sa.Column('banca', sa.String(length=50), nullable=True),
    sa.Column('prova', sa.String(length=50), nullable=True),
    sa.Column('numero_questao', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_ano'), 'questions', ['ano'], unique=False)
    op.create_index(op.f('ix_questions_banca'), 'questions', ['banca'], unique=False)
    op.create_index(op.f('ix_questions_dificuldade'), 'questions', ['dificuldade'], unique=False)
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_index(op.f('ix_questions_materia'), 'questions', ['materia'], unique=False)
    op.create_index(op.f('ix_questions_topico'), 'questions', ['topico'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ALUNO', 'PROFESSOR', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('simulados',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=True),
    sa.Column('filtros_aplicados', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulados_id'), 'simulados', ['id'], unique=False)
    op.create_table('simulado_questions',
    sa.Column('simulado_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['simulado_id'], ['simulados.id'], ),
    sa.PrimaryKeyConstraint('simulado_id', 'question_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulado_questions')
    op.drop_index(op.f('ix_simulados_id'), table_name='simulados')
    op.drop_table('simulados')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_questions_topico'), table_name='questions')
    op.drop_index(op.f('ix_questions_materia'), table_name='questions')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_dificuldade'), table_name='questions')
    op.drop_index(op.f('ix_questions_banca'), table_name='questions')
    op.drop_index(op.f('ix_questions_ano'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
