"""add_imagem_blob_column

Revision ID: 7f97a0c7c71c
Revises: 196f3771af66
Create Date: 2026-01-27 16:51:04.793950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f97a0c7c71c'
down_revision: Union[str, None] = '196f3771af66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('imagem_blob', sa.LargeBinary(), nullable=True))
    op.alter_column('questions', 'materia',
               existing_type=postgresql.ENUM('LINGUAGENS', 'HUMANAS', 'NATUREZA', 'MATEMATICA', name='materia'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'materia',
               existing_type=postgresql.ENUM('LINGUAGENS', 'HUMANAS', 'NATUREZA', 'MATEMATICA', name='materia'),
               nullable=False)
    op.drop_column('questions', 'imagem_blob')
    # ### end Alembic commands ###
